<a href="https://colab.research.google.com/github/Supragya22/Supragya22/blob/main/FakeNewsData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded=files.upload()

Saving data.csv to data.csv


In [6]:
fake=pd.read_csv('data.csv')

In [7]:
fake.head()

URLs  ... Label
0  http://www.bbc.com/news/world-us-canada-414191...  ...     1
1  https://www.reuters.com/article/us-filmfestiva...  ...     1
2  https://www.nytimes.com/2017/10/09/us/politics...  ...     1
3  https://www.reuters.com/article/us-mexico-oil-...  ...     1
4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...  ...     1

[5 rows x 4 columns]

In [8]:
fake=fake.drop(['URLs'],axis=1)
fake=fake.dropna()

In [38]:
fake.head()

Headline  ... Label
0         Four ways Bob Corker skewered Donald Trump  ...     1
1  Linklater's war veteran comedy speaks to moder...  ...     1
2  Trump’s Fight With Corker Jeopardizes His Legi...  ...     1
3  Egypt's Cheiron wins tie-up with Pemex for Mex...  ...     1
4        Jason Aldean opens 'SNL' with Vegas tribute  ...     1

[5 rows x 3 columns]

In [40]:
fake=fake[0:1000]

In [41]:
x=fake.iloc[:,:-1].values
y=fake.iloc[:,-1].values

In [42]:
x[0]

array(['Four ways Bob Corker skewered Donald Trump',
       'Image copyright Getty Images\nOn Sunday morning, Donald Trump went off on a Twitter tirade against a member of his own party.\nThis, in itself, isn\'t exactly huge news. It\'s far from the first time the president has turned his rhetorical cannons on his own ranks.\nThis time, however, his attacks were particularly biting and personal. He essentially called Tennessee Senator Bob Corker, the chair of the powerful Senate Foreign Relations Committee, a coward for not running for re-election.\nHe said Mr Corker "begged" for the president\'s endorsement, which he refused to give. He wrongly claimed that Mr Corker\'s support of the Iranian nuclear agreement was his only political accomplishment.\nUnlike some of his colleagues, Mr Corker - free from having to worry about his immediate political future - didn\'t hold his tongue.\nSkip Twitter post by @SenBobCorker It\'s a shame the White House has become an adult day care center. Som

In [43]:
y[0]

1

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
mat_body=cv.fit_transform(x[:,1]).todense()

In [45]:
mat_body

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [46]:
cv_head=CountVectorizer(max_features=5000)
mat_head=cv_head.fit_transform(x[:,1]).todense()

In [47]:
mat_head

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [48]:
x_mat=np.hstack((mat_head,mat_body))

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_mat,y,test_size=0.2,random_state=0)

In [50]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion='entropy')
dtc.fit(x_train,y_train)
y_pred=dtc.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[98,  8],
       [ 8, 86]])

In [54]:
(98+86)/(98+86+8+8)*100

92.0